version: 2

sources:
  - name: emp_dept
  {%- if  target.name == "dev" -%}
    database: dev
    schema: dbt_schema
    tables:
      - name: employee
      - name: department
  
  {%- elif target.name == "qa"  -%} 
    database: qa
    schema: dbt_schema
    tables:
      - name: employee
      - name: department
  {%- elif target.name == "prod"  -%} 
    database: prod
    schema: dbt_schema
    tables:
      - name: employee
      - name: department
  {%- else -%} invalid_database
  {%- endif -%}